title: KlimaLautern
tagline: Landkreis und Stadt Kaiserslautern klimaneutral!
url: https://klimalautern.de

author:
  name: KlimaLautern
  url: https://klimalautern.de
  twitter: KlimaLautern

plugins:
  - jekyll-feed

markdown: kramdown
